baseURL = "/"
languageCode = "es-es"
title = "SVQ Tech"
themesDir = "./themes"
theme = "hugo-serif-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "Web de las comunidades tecnológicas de Sevilla."
    meta_og_title = "SVQTech"
    meta_og_type = "website"
    meta_og_url = "https://hugo-serif.netlify.com"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
    meta_og_description = "Las comunidades tecnológicas de Sevilla."
    meta_twitter_card = "summary"
    meta_twitter_site = "@svqtech"
    meta_twitter_creator = "@mpc"

# Main Menu
[[menu.main]]
	name = "Manifiesto"
	url = "/manifiesto/"
    weight = 1

[[menu.main]]
    name = "Comunidades"
    url = "/comunidades/"
    weight = 2

[[menu.main]]
	name = "Sobre nosotros"
	url = "/sobre/"
	weight = 3

[[menu.main]]
    name = "Contacto"
    url = "/contacto/"
    weight = 4

[[menu.main]]
    name = "Evento"
    url = "/evento/"
    weight = 5

# Footer Menu
[[menu.footer]]
	name = "Inicio"
	url = "/"
    weight = 1

[[menu.footer]]
	name = "Contacto"
	url = "/contacto/"
    weight = 2
